from dataclasses import dataclass

@dataclass(frozen=True)
class Config:
    table_name: str = 'pep_table'
    desktop_dir: str = '/Users/administrator/Desktop'
    misc_dir: str = '/Users/administrator/Desktop/Misc'
    folder_dir: str = '/Users/administrator/Desktop/Misc/newFolder'
    file_dir: str = '/Users/administrator/Desktop/Misc/newFolder/newFile'
    csv_path: str = '/Users/administrator/Desktop/Projects/PythonProjects/parallel_etl_pipeline/pipeline/data.csv'
    file_name: str = 'newFile.csv'
    file_data: str = """
                "among","cast","nearer","average","order","image","shown","got","post","running","younger","experiment","gave","grown","income","does","independent","people","cake","garage","birth","steady","highway","deep","recognize","horn","toward","former","report","show"
                "smile","eaten","discovery","language","troops","sometime","pen","frequently","throat","yet","valley","join","instead","use","silence","hunter","eye","original","shorter","bean","spite","century","account","excellent","equator","gate","ability","weigh","instance","personal"
                "actual","solar","pride","care","program","border","flight","garden","language","common","high","top","size","solution","golden","seeing","lost","actually","situation","got","hung","event","dear","contrast","physical","owner","distant","slow","dot","care"
                "is","thin","atomic","would","she","basic","goes","trick","snake","no","fierce","listen","plane","answer","afraid","luck","monkey","slide","only","vast","merely","nearby","native","seldom","floor","respect","taste","too","troops","with"
                "rear","height","fix","market","find","fairly","deep","cover","organization","interest","salmon","failed","weak","something","take","told","silly","evidence","worker","printed","browserling","door","wild","flies","struggle","compass","clothing","human","bound","by"
                "remove","silver","else","ranch","rain","leaving","had","wall","dance","happened","teacher","wolf","great","average","never","moment","sail","tears","rice","her","diagram","word","figure","affect","phrase","throw","tightly","fireplace","guess","private"
                "eventually","fear","meet","position","chart","track","hold","die","bar","steel","corn","gently","experience","valley","which","couple","captain","farm","root","guard","position","positive","factor","hair","bread","consider","add","particular","friendly","few"
                "largest","atmosphere","easier","whether","dried","after","truck","string","sharp","everything","various","lay","torn","not","record","safe","hall","solve","recently","today","know","through","wagon","organized","search","aloud","question","tall","due","empty"
                "party","late","dog","mix","highest","key","where","there","same","explore","warn","accept","honor","they","gold","opinion","bus","small","social","nothing","house","toy","live","giving","bow","money","effect","weight","tales","weight"
                "last","mix","men","enjoy","valley","own","spring","acres","period","certain","milk","breathe","either","game","everybody","universe","pack","traffic","coach","voyage","mysterious","image","fallen","fall","heat","shorter","fellow","porch","chain","instant"
                "deep","strange","length","can","ourselves","golden","various","model","eaten","talk","bear","product","triangle","happy","dog","accept","mice","port","note","victory","subject","exercise","welcome","difficulty","began","grain","quickly","lake","origin","exact"
                "join","answer","softly","driving","lonely","consonant","lower","stronger","but","struggle","land","tell","with","angle","measure","soap","both","current","this","elephant","welcome","biggest","movie","degree","rice","situation","open","that","expression","ran"
                "skin","beauty","composition","lips","variety","roar","perfect","practical","dream","introduced","soap","therefore","anyway","element","physical","effect","against","could","sort","level","characteristic","history","salmon","plates","grow","outside","perfect","write","pure","join"
                "broken","corn","television","blow","bus","daily","nails","cap","reader","setting","shallow","copy","accept","activity","were","attention","bit","belt","funny","ever","been","shelf","native","sea","by","state","color","number","weight","apart"
                "whistle","learn","combine","lying","silver","experiment","sign","eight","compass","or","spin","husband","rate","library","cover","bus","house","cover","kids","why","consist","nation","had","run","until","circus","angle","front","wheat","carried"
                "when","border","opportunity","trip","success","front","promised","fast","couple","immediately","feet","stock","noun","chain","record","nation","settlers","terrible","some","tower","receive","break","my","struck","rise","farther","finally","think","quiet","battle"
                "experiment","largest","graph","spend","branch","each","running","brother","voice","pleasant","average","purpose","pattern","forty","adventure","library","friend","sent","headed","other","offer","girl","whispered","reach","gave","dig","branch","parts","poem","point"
                "another","else","forth","solar","future","consonant","until","may","storm","dish","bank","congress","noun","motor","live","chemical","courage","cannot","myself","having","asleep","gulf","result","paint","anyway","pen","purple","labor","heart","experiment"
                "valley","brain","range","supply","one","class","still","sentence","spider","nearly","immediately","beyond","country","chair","mine","town","becoming","introduced","unless","empty","desert","equal","period","involved","lying","market","range","brought","danger","carbon"
                "knowledge","solution","biggest","danger","circle","rather","broken","generally","upper","general","favorite","fireplace","shelter","naturally","floor","begun","develop","strength","enter","rocket","ought","past","search","please","joined","seed","broke","structure","usual","tongue"
                "tail","journey","table","organized","wave","courage","close","teeth","eventually","control","sides","threw","farm","hunt","closely","clean","behavior","grass","gasoline","note","sale","variety","bare","parts","deer","loss","soldier","college","muscle","melted"
                "upward","fish","happily","discuss","likely","case","tie","cookies","create","to","morning","prove","roll","metal","spider","tin","forgotten","son","struck","neighborhood","thrown","material","thumb","say","dozen","pictured","thy","whether","bow","handsome"
                "spite","back","into","certain","stay","heart","general","whatever","dull","fly","nearly","me","leader","happy","down","hard","worried","animal","changing","fallen","notice","correct","bowl","hospital","hardly","begun","quietly","root","pass","those"
                "desert","think","met","exercise","hope","business","camp","yard","shade","nation","among","journey","expect","listen","meat","gate","excitement","pleasant","shadow","thee","fill","kitchen","plastic","available","now","card","rod","split","nest","handle"
                "sail","angry","guide","ruler","excitement","film","busy","east","animal","military","sudden","quietly","visitor","hearing","volume","species","sat","pine","mean","end","plant","dollar","driving","strength","vessels","moon","maybe","giant","caught","spoken"
                "victory","develop","writer","low","field","rule","cotton","pick","note","usual","numeral","speed","current","invented","swim","way","first","instead","dust","me","measure","quarter","product","shinning","company","already","taste","drive","highway","soon"
                "upward","green","outer","smaller","lunch","face","explore","trail","rise","note","construction","instead","flies","program","tank","whom","shelf","hand","box","repeat","research","just","collect","surface","chance","shore","loss","motion","salt","detail"
                "take","frighten","brush","sum","likely","trail","comfortable","law","wish","rock","experiment","burn","mirror","process","anywhere","lying","disappear","hole","space","soon","member","sure","solve","pupil","trap","baby","door","each","rocky","information"
                "easier","hundred","accident","primitive","frame","continent","layers","similar","teach","sport","step","wherever","using","youth","save","sort","very","fair","bad","above","branch","avoid","spread","riding","stick","sing","single","sentence","wire","star"
                "alone","hidden","individual","mouth","cloth","twelve","leave","split","sight","life","spread","strong","kept","easily","idea","exciting","hand","broken","wheel","balance","bad","original","knew","actual","winter","variety","colony","raw","molecular","fifteen"
                "flag","gold","ask","indeed","told","master","mice","gather","settle","remember","coat","loose","wagon","state","bone","carry","plan","indicate","rabbit","related","hollow","joy","radio","putting","western","were","drive","bet","stiff","court"
                """  